name: main

on: [push, pull_request]

jobs:
  pack:
    runs-on: windows-latest
    permissions:
      actions: write
      contents: read

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Publish
        run: >
          dotnet publish YoutubeDownloader
          --output YoutubeDownloader/bin/publish
          --configuration Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: YoutubeDownloader
          path: YoutubeDownloader/bin/publish

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: pack
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: YoutubeDownloader
          path: YoutubeDownloader

      - name: Create package
        shell: pwsh
        run: >
          Compress-Archive
          -Path YoutubeDownloader/*
          -DestinationPath YoutubeDownloader.zip
          -Force

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create "${{ github.ref_name }}"
          "YoutubeDownloader.zip"
          --repo "${{ github.event.repository.full_name }}"
          --title "${{ github.ref_name }}"
          --notes "[Changelog](${{ github.event.repository.html_url }}/blob/${{ github.ref_name }}/Changelog.md)"
          --verify-tag

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Notify Discord
        uses: tyrrrz/action-http-request@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            Content-Type: application/json; charset=UTF-8
          body: |
            {
              "content": "**${{ github.event.repository.name }}** new version released!\nVersion: `${{ github.ref_name }}`\nChangelog: <${{ github.event.repository.html_url }}/blob/${{ github.ref_name }}/Changelog.md>"
            }